### ISSUE TITLE
Some users of my app reported that the tvOS screensaver shows while they are watching a movie

### ISSUE THREAD

**Issue by soymonitus** [kodlian/TVVLCPlayer#20]
I push the viewcontroller in the navigationcontroller to show it fullscreen, the class VLCPlayerViewController set the view of the VLCPlayer with the UIView that occupies the full screen.
Some users experiment this issue that the screensaver shows.

Do i need to do?
UIApplication.shared.isIdleTimerDisabled = false  in viewWillAppear
UIApplication.shared.isIdleTimerDisabled = true in viewWillDissapear

**Comment by kodlian** [comment]
Sorry for the late reply, indeed it seems that you need to do that operation for avoiding the screensaver. The best will be actually to link to the state of the player (only disabled when the video is playing)
