### ISSUE TITLE
Video Plays after few seconds of audio play

### ISSUE THREAD

**Issue by wertpoiu** [kodlian/TVVLCPlayer#21]
As title states video plays late than audio, plus zapping time is too much.

**Comment by kodlian** [comment]
If you encounter issues with the playing, it is not related to this framework but rather the embedded VLCKit framework. You should investigate the issue with your media with the VLC community https://code.videolan.org/videolan/VLCKit. But first, you may try to update the version embed in TVVLCPlayer (updating pod dependency or Carthage on VLCKit) to check if they have fixed it already. I will be happy to merge the update.
