### ISSUE TITLE
Complication error with Cocoapods 1.5

### ISSUE THREAD

**Issue by weiran** [kodlian/TVVLCPlayer#5]
Using Cocoapods 1.5, I get the following error when trying to build or use TVVLCPlayer: `using bridging headers with framework targets is unsupported` The error doesn't occur with Cocoapods 1.4.

The only big difference I can find is 1.4 sets TVVLCPlayer's product type as a static library, while 1.5 sets it as a framework. Once I set the `productType` to `com.apple.product-type.library.static` and add the 'Setup Static Framework' build phase back in the project file, the library then compiles fine.

**Comment by kodlian** [comment]
Since TVVLCKit is no longer builded as a static library, the podspec isn't correct especially the bridge header injection and ressources bundle. I will do my possible to make it build again.

**Comment by robbiet480** [comment]
I was able to fix this issue by adding `:modular_headers => true` to the TVVLCPlayer line in my Podfile

**Comment by robbiet480** [comment]
I was able to fix this by adding `'DEFINES_MODULE' => 'YES'` in the Podspec `pod_target_xcconfig`.

**Comment by robbiet480** [comment]
CORRECTION: `DEFINES_MODULE` should be set to `NO`. The Podfile `post_install` hook in my earlier comment did a similar thing by setting deleting the property entirely which caused it to fallback to what I believe is the CocoaPods default of NO.

**Comment by ndcg91** [comment]
> I was able to fix this by adding `'DEFINES_MODULE' => 'YES'` in the Podspec `pod_target_xcconfig`.
> 
> Alternatively, add a `post_install` hook to your Podfile like this:
> 
> ```ruby
> post_install do |installer|
>     installer.pods_project.targets.each do |target|
>         target.build_configurations.each do |config|
>             if target.name == 'TVVLCPlayer' or target.name == 'TVVLCPlayer-TVVLCPlayer'
>                 config.build_settings.delete('DEFINES_MODULE')
>             end
>         end
>     end
> end
> ```

It works for me on the build phase but I am unable to archive with this settings. It gave me the same error on the archive phase.

**Comment by kodlian** [comment]
Sorry I didn't have time to work on this before. But I just made some changements to the framework to make it work as a dynamic framework:
https://github.com/kodlian/TVVLCPlayer/releases/tag/1.1.0

It works better with Carthage, but you can use coco pods using the following workaround:
```ruby
pod ":git => 'https://github.com/kodlian/TVVLCPlayer.git', :tag => "1.1.0"

pre_install do |installer|
	# workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
	Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
end
```

I also opened a PR to the VLCKit project to add the module compatibility.

**Comment by weiran** [comment]
Thanks for the updates! I've tried with the new Cocoapods method on 1.1.1 but I now get the following linker error during compilation:

```linker command failed with exit code 1```

I tried with a fresh tvOS project with just TVVLCPlayer as a dependency, and have the same error. I can provide the full output but I'm not sure how useful it is.

**Comment by kodlian** [comment]
Please could you provide the full log. 
Do you use Xcode 10?
If it is compatible with your projects, I recommend to use the Carthage (I have less issue with this method).

**Comment by weiran** [comment]
I'm using latest Xcode 10.1 and Cocoapods 1.5.3. I've uploaded a basic project which demonstrates this problem for me: https://github.com/weiran/TVVLCPlayerTest

I've put the log output here: https://gist.github.com/weiran/ee59962371d5d6ed824e59b562d158c0

I'll give Carthage a try, although every other dependency is managed through Cocoapods and I was hoping to keep dependency management in one place.

**Comment by weiran** [comment]
So I tried Carthage, and during `carthage upgrade` the ruby process used all 24GB of RAM and hung my system. Not sure if that's a Carthage bug or if it found some circular dependency causing a problem there.

I've tried adding those dependencies to both my project and the Pods project but I still get the same linker error. I'll keep trying.

**Comment by weiran** [comment]
> In the meantime try to add them to your main project.

I just tried adding those frameworks and libraries to the Pod project and it now builds. Maybe they need to be explicitly defined in the `podfile`?

**Comment by kodlian** [comment]
@weiran I'm not familiar enough with the pod file spec. Is there a way to add dependencies for system library etc? 
If we can automate that it could be great.

**Comment by weiran** [comment]
@kodlian with #15 and #16 merged this now builds when pulled in with Cocoapods. You can validate this with your demo project.
